### ISSUE TITLE
Button label when not using display group

### ISSUE THREAD

**Issue by Hagith** [Emagister/zend-form-decorators-bootstrap#9] opened 2012-03-30 09:52 UTC
As you can see on [the screen](https://github.com/rafalgalka/zend-form-decorators-bootstrap/blob/6b62bcee0c82ba11beabe8e6e5362577e452194b/vertical-horizontal-after-inheritance-fix.png) there is a problem with button label when not using dedicated DisplayGroup.

**Comment by theUniC** [comment] 2012-08-28 14:19
Can you paste an example code please? In order to reproduce the issue?

Thanks,
Christian.

**Comment by theUniC** [comment] 2012-08-30 05:21
Unable to reproduce without a code example. Closing for now. Will reopen when needed.

**Closed as completed by theUniC** 2012-08-30 05:21 UTC
